language: java
jdk: oraclejdk11

before_script:
  - psql -c "CREATE DATABASE flixbus_db;" -U postgres
  - psql -c "CREATE USER newarcher WITH PASSWORD 'newarcher_password';" -U postgres

before_install:
  - docker build -t newarcher/miniproject-test -f Dockerfile.dev .

matrix:
  include:
    - jdk: openjdk11

services:
  - docker
  - postgresql

addons:
  hosts:
    - postgres
#env:
#  global:
#    - POSTGRES_DB=flixbus_db
#    - POSTGRES_USER=newarcher
#    - POSTGRES_PASSWORD=newarcher_password

#script:
#  - ./mvnw clean deploy -B

after_success:
  - docker build -t newarcher36/miniproject -f .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push newarcher36/miniproject

#deploy:
#  edge: true
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "miniproject"
#  env: "Miniproject-env"
#  bucket_name: "elasticbeanstalk-us-east-2-625283505629"
#  bucket_path: "miniproject"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY

