sudo: required

language: java
jdk: oraclejdk9

matrix:
  include:
    - jdk: openjdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

services:
  - docker

script:
  - ./mvnw clean install -B

after_success:
  - docker build -t newarcher36/miniproject -f Dockerfile.dev .

deploy:
  project: elasticbeanstalk
  region: "us-east-2"
  app: "miniproject"
  env: "Miniproject-env"
  bucket_name: "elasticbeanstalk-us-east-2-625283505629"
  bucket_path: "miniproject"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  deploy:
    edge: true
    provider: elasticbeanstalk

