os: linux

language: java
jdk: oraclejdk11

addons:
  hosts:
    - postgres

before_install:
  - psql -c "CREATE DATABASE flixbus_db;" -U postgres
  - psql -c "CREATE ROLE archer WITH PASSWORD 'archer_password';" -U postgres

#before_install:
#  - docker-compose up -f docker-compose.dev.yml

matrix:
  include:
    - jdk: openjdk11

services:
  - docker
  - postgresql


env:
  global:
    - POSTGRES_DB=flixbus_db
    - POSTGRES_USER=archer
    - POSTGRES_PASSWORD=archer_password

script:
  - docker build -t archer/miniproject-test -f Dockerfile.dev .
#  - ./mvnw clean deploy -B

after_success:
  - docker build -t archer36/miniproject -f .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push archer36/miniproject

#deploy:
#  edge: true
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "miniproject"
#  env: "Miniproject-env"
#  bucket_name: "elasticbeanstalk-us-east-2-625283505629"
#  bucket_path: "miniproject"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY

