os: linux

language: java
jdk: oraclejdk11

addons:
  hosts:
    - postgres

before_install:
  - psql -c "CREATE DATABASE flixbus_db;" -U postgres
  - psql -c "CREATE ROLE archer WITH LOGIN PASSWORD 'archer_password';" -U postgres

#before_install:
#  - docker-compose up -f docker-compose.dev.yml

matrix:
  include:
    - jdk: openjdk11

services:
  - docker
  - postgresql


env:
  global:
    - POSTGRES_DB=flixbus_db
    - POSTGRES_USER=archer
    - POSTGRES_PASSWORD=archer_password

script:
#  - docker build -t archer/miniproject-test -f Dockerfile.dev .
  - ./mvnw clean install

after_success:
  - docker build -t archer36/miniproject -f .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push archer36/miniproject


