sudo: required

language: java
jdk: oraclejdk9

matrix:
  include:
    - jdk: openjdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

services:
  - docker

script:
  - ./mvnw clean install -B

after_success:
  - docker build -t newarcher36/miniproject -f Dockerfile.dev .