version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=flixbus_db
      - POSTGRES_USER=newarcher
      - POSTGRES_PASSWORD=newarcher_password
  builder-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    extra_hosts:
      - "postgres:127.0.0.1"
    depends_on:
      - postgres