version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=flixbus_db
      - POSTGRES_USER=archer
      - POSTGRES_PASSWORD=archer_password
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./target:/usr/app/
    image: miniproject
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres