version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=flixbus_db
      - POSTGRES_USER=newarcher
      - POSTGRES_PASSWORD=newarcher_password
  server:
    depends_on:
      - "postgres"
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: miniproject-test