version: '3'
services:
  postgres:
    image: 'postgres:latest'
  server:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432