version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=flixbus_db
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./target:/usr/app/
    image: miniproject
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      - POSTGRES_DB=flixbus_db
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432