version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=flixbus_db
      - POSTGRES_USER=newarcher
      - POSTGRES_PASSWORD=newarcher_password
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./target:/usr/app/
    image: miniproject
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres