spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:flixbus;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: dev